# Generated by Django 3.0.5 on 2020-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20200916_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
